coverage:
  range: 50..60
  round: up
  precision: 2

ignore:
  - "src/server/server.js"
  - "src/index.js"
  - "src/views/arena-main.js"
  - "components/datagridAdminCompetitions.js"
  - "components/datagridArenaLeaderboard.js"
  - "src/views/admin-competitions.js"