coverage:
  range: 50..60
  round: up
  precision: 2

ignore:
  - "src/server/server.js"
  - "src/index.js"
  - "src/views/arena-main.js"
  - "src/views/arena-team.js"
  - "src/views/arena-leaderboard.js"