coverage:
  range: 70..80
  round: up
  precision: 2

ignore:
  - "src/server/server.js"
  - "src/index.js"
  - "src/views/arena-main.js"
  - "src/components/datagridAdminCompetitions.js"
  - "src/components/datagridArenaLeaderboard.js"
  - "src/components/datagridAdminTeams.js"
  - "src/views/arena-submissions.js"
  - "src/views/leaderboard.js"
  - "src/views/arena-team.js"
  - "src/views/player-portal-team.js"
  - "src/views/register.js"
  - "src/views/teams.js"
  - "src/views/admin-competitions.js"
  - "src/views/arena-leaderboard.js"
  - "src/views/contact.js"
  - "src/views/login.js"
