version: 2.1

orbs:
  node: circleci/node@4.7
  jira: circleci/jira@1.3.1

workflows:
  sample:
    jobs:
      - node/test:
          version: "16.10"
          pkg-manager: npm
          post-steps:
            - jira/notify
          parallelism: 1
          steps:
            - run:
                name: Run tests with coverage
                command: npm run test -- --coverage --watchAll=false