name: Codecov
run-name: ${{ github.actor }} is testing out Codecov
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
