name: Codecov CI

on:
  push:
    branches:
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Codecov

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
          
      - name: Run tests and collect coverage
        run: npm test -- --coverage --watchAll=false
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
